// API V1 导航配置
export const apiV1Sections = [
  { id: 'controls', title: '自动化 - 控件操作' },
  { id: 'coordinates', title: '自动化 - 坐标操作' },
  { id: 'app', title: 'app - 应用' },
  { id: 'base64', title: 'base64' },
  { id: 'colors', title: 'colors - 颜色' },
  { id: 'canvas', title: 'canvas - 画布' },
  { id: 'console', title: 'console - 控制台' },
  { id: 'crypto', title: 'crypto - 加解密与消息摘要' },
  { id: 'debug', title: 'debug - 调试工具' },
  { id: 'device', title: 'device - 设备' },
  { id: 'dialogs', title: 'dialogs - 对话框' },
  { id: 'engines', title: 'engines - 脚本引擎' },
  { id: 'events', title: 'events - 事件与监听' },
  { id: 'floaty', title: 'floaty - 悬浮窗' },
  { id: 'files', title: 'files - 文件系统' },
  { id: 'globals', title: 'globals - 全局变量与函数' },
  { id: 'http', title: 'http - HTTP网络请求' },
  { id: 'images', title: 'images - 图片处理' },
  { id: 'keys', title: 'keys - 按键模拟' },
  { id: 'media', title: 'media - 多媒体' },
  { id: 'module', title: 'module - 模块' },
  { id: 'ocr', title: 'ocr - 文字识别' },
  { id: 'plugins', title: 'plugins - 插件' },
  { id: 'power_manager', title: 'power_manager - 电源管理' },
  { id: 'sensors', title: 'sensors - 传感器' },
  { id: 'shell', title: 'shell - Shell命令' },
  { id: 'storages', title: 'storages - 本地存储' },
  { id: 'settings', title: 'settings - 设置' },
  { id: 'threads', title: 'threads - 多线程' },
  { id: 'thirdPartyPlugins', title: 'thirdPartyPlugins - 第三方插件' },
  { id: 'timers', title: 'timers - 定时器' },
  { id: 'work_manager', title: 'work_manager - 定时与任务' },
  { id: 'ui-module', title: 'ui - 用户界面' },
  { id: 'util', title: 'util - 工具' },
  { id: 'websocket', title: 'WebSocket' },
  { id: 'zip', title: 'zip - 压缩与解压' },
  { id: 'java', title: '和Java交互' }
]

